"""second migrate

Revision ID: c45385f85b0f
Revises: 4a10654cb2bb
Create Date: 2024-10-19 11:27:01.244891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c45385f85b0f'
down_revision: Union[str, None] = '4a10654cb2bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'formulas', 'medicamentos', ['medicamento_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'formulas', type_='foreignkey')
    # ### end Alembic commands ###
